// for changes to bring to Minecraft 26.1.2, see https://github.com/architectury/architectury-loom/issues/328

plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "dev.architectury.loom-no-remap" version "${loom_version}" apply false
}

architectury {
    minecraft = project.minecraft_version
}

subprojects {
    apply plugin: "java-library"

    java.toolchain.languageVersion = JavaLanguageVersion.of(25)

    tasks.withType(JavaCompile).configureEach {
    options.release = 25
    }

    compileJava.options.encoding = compileTestJava.options.encoding = javadoc.options.encoding = "UTF-8"

    repositories {
        mavenCentral()
        maven { url = uri('https://maven.fabricmc.net/') }
        maven { url = uri('https://maven.nucleoid.xyz') }
        maven { url = uri('https://oss.sonatype.org/content/repositories/snapshots') }
    }

    java {
        withSourcesJar()
    }
}

configure(subprojects) {
    apply plugin: "architectury-plugin"
    apply plugin: "dev.architectury.loom-no-remap"

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
    }
}
