pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'mobfilter'
include 'common'
include 'fabric'
//include 'neoforge'
