
pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "fastback"

include(":common")
include(":fabric")

// NOTE: Forge is no longer supported and the build has been disabled
// See: https://github.com/pcal43/fastback/issues/333
// include(":forge")
